// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP svmod_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// lineCount
long lineCount(std::string fName);
RcppExport SEXP svmod_lineCount(SEXP fNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fName(fNameSEXP);
    rcpp_result_gen = Rcpp::wrap(lineCount(fName));
    return rcpp_result_gen;
END_RCPP
}
// subSampleFastq
int subSampleFastq(std::string fqR1Name, std::string fqR2Name, unsigned long nbrDesiredReads, std::string fOutName);
RcppExport SEXP svmod_subSampleFastq(SEXP fqR1NameSEXP, SEXP fqR2NameSEXP, SEXP nbrDesiredReadsSEXP, SEXP fOutNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fqR1Name(fqR1NameSEXP);
    Rcpp::traits::input_parameter< std::string >::type fqR2Name(fqR2NameSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type nbrDesiredReads(nbrDesiredReadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type fOutName(fOutNameSEXP);
    rcpp_result_gen = Rcpp::wrap(subSampleFastq(fqR1Name, fqR2Name, nbrDesiredReads, fOutName));
    return rcpp_result_gen;
END_RCPP
}
