# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('svmod_rcpp_hello_world', PACKAGE = 'svmod')
}

#' Counts the lines of a text file.
#' 
#' @param fName file name
#' @return The number of lines
#' @export
lineCount <- function(fName) {
    .Call('svmod_lineCount', PACKAGE = 'svmod', fName)
}

#' Sub-samples reads from a FASTQ-file.
#' 
#' @param fName file name of FASTQ-file
#' @export
subSampleFastq <- function(fName) {
    .Call('svmod_subSampleFastq', PACKAGE = 'svmod', fName)
}

