# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('svmod_rcpp_hello_world', PACKAGE = 'svmod')
}

#' Counts the lines of a text file.
#' 
#' @param fName file name
#' @return The number of lines
#' @export
lineCount <- function(fName) {
    .Call('svmod_lineCount', PACKAGE = 'svmod', fName)
}

#' Sub-samples reads from a FASTQ-file.
#' 
#' @param fqR1Name file name of R1-FASTQ-file
#' @param fqR2Name file name of R2-FASTQ-file
#' @param nbrDesiredReads long number of reads to sample from FASTQ file
#' @param fOutName file name for output
#' @export
subSampleFastq <- function(fqR1Name, fqR2Name, nbrDesiredReads, fOutName) {
    .Call('svmod_subSampleFastq', PACKAGE = 'svmod', fqR1Name, fqR2Name, nbrDesiredReads, fOutName)
}

